### ISSUE TITLE
Is it possible to transfer data between pyqgis plugins?

### ISSUE THREAD

**Issue by zacwang89** [qgis/pyqgis#69]
I'm not sure if this is a right place to ask the question. Since I asked my question in QT forum, but no one could answer it.

Is there a way to send signals among different plugins directly to make them communicate?

Thanks in advance.

**Comment by luipir** [comment]
yes this is not the right place. You should use qgis-developer mailing list (I'll close it because is not an issue and it's in the wrong place)
BTW your question is not related with QGIS or QT or python bue with generic inter process communication that can be implemented in very very many ways.

regards

**Comment by zacwang89** [comment]
Hi @luipir, sorry for posting in the wrong place and thanks for your advice on using mailing list.

**Comment by luipir** [comment]
no problem :)
